---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: centos-6.6

suites:
  - name: default
    driver_config:
      customize:
        memory: 1024
      network:
        - ["private_network", {ip: "192.168.33.35"}]
    run_list:
      - recipe[influxdb::default]
      - recipe[influxdb-test::default]
    # Uncomment below if testing data bags needed
    # data_bags_path: test/integration/data_bags
    attributes:
